/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Basharat
 */
public class deposit extends javax.swing.JFrame {

    /**
     * Creates new form deposit
     */
                deposit_data obj=new deposit_data();

    public deposit() {
        initComponents();
        
        
        ImageIcon imagee=new ImageIcon("deposit.jpg");
        Image ime=imagee.getImage();
        Image dime=ime.getScaledInstance(back.getWidth(),back.getHeight(), Image.SCALE_SMOOTH);
        imagee=new ImageIcon(dime);
       back.setIcon(imagee);
        
        try {
            date();
            System.out.println(obj.getBlnc());
            obj.blnc_get();
            blnc.setText(obj.getBlnc());
//             balance();
        } catch (Exception ex) {
            Logger.getLogger(deposit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void date() throws Exception {
        DateTimeFormatter dat = DateTimeFormatter.ofPattern("d-M-yyyy");
        LocalDateTime datee = LocalDateTime.now();
        String dr = dat.format(datee);

        dt.setText(dr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        amount = new javax.swing.JTextField();
        btndeposit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        blnc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deposit");
        setBackground(new java.awt.Color(153, 255, 153));
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountMouseClicked(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountKeyTyped(evt);
            }
        });
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, 40));

        btndeposit.setBackground(new java.awt.Color(51, 204, 255));
        btndeposit.setText("Deposit");
        btndeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndepositMouseEntered(evt);
            }
        });
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });
        jPanel1.add(btndeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 79, 42));

        jButton1.setText("Main");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Balance:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        blnc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(blnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Date:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 30));

        dt.setForeground(new java.awt.Color(0, 0, 0));
        dt.setText("jLabel3");
        jPanel1.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 30));

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Amount:");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 30));

        back.setText("jLabel3");
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 352, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        show_data obj=new show_data();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed

        if(amount.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter Amount to deposit");
        }
        else if(!amount.getText().matches("[0-9]{2,5}")){
            JOptionPane.showMessageDialog(this, "Invalid Amount.You can deposit amount maximum in thusands ");
        }
        
        
        else{
 
 
                   ImageIcon imagee=new ImageIcon("depimag.jpg");
        Image ime=imagee.getImage();
        Image dime=ime.getScaledInstance(back.getWidth(),back.getHeight(), Image.SCALE_SMOOTH);
        imagee=new ImageIcon(dime);
       back.setIcon(imagee);
 
       
            
        obj.setBlnc(blnc.getText());
        obj.setAmount(amount.getText());
        obj.setDate(dt.getText());

        obj.insert();
        obj.blnc_get();
        blnc.setText(obj.getBlnc());
        amount.setText("");
        }
    }//GEN-LAST:event_btndepositActionPerformed

    private void amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_amountKeyTyped

    private void amountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_amountMouseClicked

    private void btndepositMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepositMouseEntered
        // TODO add your handling code here:
        Cursor p=new Cursor(Cursor.HAND_CURSOR);
        btndeposit.setCursor(p);
    }//GEN-LAST:event_btndepositMouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
          Cursor p=new Cursor(Cursor.HAND_CURSOR);
       jButton1.setCursor(p);
        
    }//GEN-LAST:event_jButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deposit().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel back;
    public static javax.swing.JLabel blnc;
    private javax.swing.JButton btndeposit;
    private javax.swing.JLabel dt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
