/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user_interface;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.PointerInfo;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Basharat
 */
public class signup extends javax.swing.JFrame {

    connectdb db = new connectdb();

    public signup() {
        initComponents();

        ImageIcon imagee = new ImageIcon("signb.jpg");
        Image ime = imagee.getImage();
        Image dime = ime.getScaledInstance(back.getWidth(), back.getHeight(), Image.SCALE_SMOOTH);
        imagee = new ImageIcon(dime);
        back.setIcon(imagee);

        try {

            db.conect_to_db();

        } catch (Exception e) {
            System.out.println("Connected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        cname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caccount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ccnic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        deposit = new javax.swing.JTextField();
        pin1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        pin2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOINING FORM");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnameKeyTyped(evt);
            }
        });
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 50, 20));

        caccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caccountKeyTyped(evt);
            }
        });
        getContentPane().add(caccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Card number:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CNIC:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, -1));

        ccnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ccnicKeyTyped(evt);
            }
        });
        getContentPane().add(ccnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inital Deposit:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        deposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                depositKeyTyped(evt);
            }
        });
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 277, 140, 30));

        pin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pin1KeyTyped(evt);
            }
        });
        getContentPane().add(pin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pin:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
        getContentPane().add(pin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Retype Pin:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        signup.setBackground(new java.awt.Color(51, 255, 51));
        signup.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        signup.setText("Activate Now");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
        });
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        signup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signupKeyPressed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 130, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("      Welcome to Card Activation");
        jLabel1.setPreferredSize(new java.awt.Dimension(275, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 280, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Cancel");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 100, 40));

        back.setText("jLabel3");
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameKeyTyped

    private void cnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameKeyPressed

    private void pin1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pin1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_pin1KeyTyped

    private void ccnicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ccnicKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_ccnicKeyTyped

    private void depositKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_depositKeyTyped

    private void caccountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caccountKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_caccountKeyTyped

    private void signupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_signupKeyPressed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:

        String pin1=this.pin1.getText();
        String pin2=this.pin2.getText();
        System.out.println("pin 1 "+pin1);
        System.out.println("pin 1 "+pin2);
        if (cname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name can not be empty");

        } //         String cnic=ccnic.getText();
       
         else if (cname.getText().length()<3) {
            JOptionPane.showMessageDialog(this, "Please enter at least 3 letter name");
        }
          else if (!cname.getText().matches("[A-Za-z ]{3,}")) {
            JOptionPane.showMessageDialog(this, "Sorry only Alphabets and spaces alowed in Name");
        } 
        else if (caccount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your Card number ");

        }
        else if (!caccount.getText().matches("[0-9]{6}")) {
            JOptionPane.showMessageDialog(this, "Card number must contain 6 digits");
        }

        else if (ccnic.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your CNIC number");

        }
        else if (!ccnic.getText().matches("[0-9]{13}")) {
            JOptionPane.showMessageDialog(this, "Cnic must contain 13 digits "+ccnic.getText().length()+" are written");
        }

        else if (deposit.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pleas enter Initial deposit");

        }
        else if (!ccnic.getText().matches("[0-9]{3,}")) {
            JOptionPane.showMessageDialog(this, "Pleas enter Amount in thousand");
        }

        else if (pin1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your PIN");

        }

        else if (!pin1.matches("[0-9]{4,}")) {
            JOptionPane.showMessageDialog(this, "Minimum 4 letters pin sholud be written");
        }

        else if (pin2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Conform  your PIN");

        }
        else if (!pin2.equals(pin1)) {
                Icon icon = new javax.swing.ImageIcon("F:\\netbeans\\netbeans projects\\Allied\\ic.png");
                JOptionPane.showMessageDialog(this, "PIN Does Not Match", "Authentication", HEIGHT, icon);
            }

        else {
            siignupdata sign = new siignupdata();

            sign.setAccount_number(caccount.getText());

            sign.setName(cname.getText());

            sign.setCnic(ccnic.getText());

//             else {
                sign.setPas(pin1);
//            }
            sign.setDeposit(deposit.getText());
            try {
                //           sign.match();
                sign.insert();
                sign.tbluser();
            } catch (Exception ex) {
                Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
            }

            login lg = new login();
            lg.setVisible(true);
            this.dispose();
            ccnic.setText("");
            caccount.setText("");
            caccount.setText("");
            deposit.setText("");
            cname.setText("");
            this.pin1.setText("");
            this.pin2.setText("");
        }
        //        login obj=new login();
        //        obj.setVisible(true);
        //        this.dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        // TODO add your handling code here:

        Cursor p=new Cursor(Cursor.HAND_CURSOR);
        signup.setCursor(p);
    }//GEN-LAST:event_signupMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField caccount;
    private javax.swing.JTextField ccnic;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField deposit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pin1;
    private javax.swing.JPasswordField pin2;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
